# This file was generated by GoReleaser. DO NOT EDIT.
cask "raph" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "6ea3f1ed16e7ccd809c4daa47708a3f4fbe55c8dab68172ee1e0da502b558425"
      url "https://github.com/tesh254/raph/releases/download/v#{version}/raph_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6e04d132ef2ca3ba964afa9ea8f26c887ebd730fe28ef8c355d107820410c852"
      url "https://github.com/tesh254/raph/releases/download/v#{version}/raph_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f9f9d61a459ace5eaf42485165bd1df96e9fb0cf4afc8aa7c4c0366ca5f256b5"
      url "https://github.com/tesh254/raph/releases/download/v#{version}/raph_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bed27a082a8699d8e9316b63ff7e52c7f6b0534143077289c4915492ddc75832"
      url "https://github.com/tesh254/raph/releases/download/v#{version}/raph_linux_arm64.tar.gz"
    end
  end

  name "raph"
  desc "Local-first graph-vector brain for coding agents"
  homepage "https://tesh254.github.io/raph/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "raph"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/raph"]
    end
  end

  # No zap stanza required

end
