# This file was generated by GoReleaser. DO NOT EDIT.
cask "raph" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "1d04af7db2a1bb2bd6bdd86510d7a2191ef955c37dfa06fa23e4a0cbc85a12e6"
      url "https://github.com/tesh254/raph/releases/download/v#{version}/raph_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0e62bf278a7c4d0741c3587d7b8fb64007457cf13b27a7c50a2c5c4f26966e65"
      url "https://github.com/tesh254/raph/releases/download/v#{version}/raph_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6fbcbc4abfa97a3272fd4363ff19d74f785d1ab67bfc05bd11a55556c19ed895"
      url "https://github.com/tesh254/raph/releases/download/v#{version}/raph_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "debc5cef809d4d88d3d8d8502d6434b7685c893f0ef7db26686d0f249e0f5477"
      url "https://github.com/tesh254/raph/releases/download/v#{version}/raph_linux_arm64.tar.gz"
    end
  end

  name "raph"
  desc "Local-first graph-vector brain for coding agents"
  homepage "https://tesh254.github.io/raph/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "raph"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/raph"]
    end
  end

  # No zap stanza required

end
