# This file was generated by GoReleaser. DO NOT EDIT.
cask "raph" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "93a8046d0c3c941ad7c75a4e57c330131ec1a500ff4486142322cc8b0fca3e30"
      url "https://github.com/tesh254/raph/releases/download/v#{version}/raph_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "040ed1834de555af8e18b548c9b86bc67932be1d8a2cca2e08bcda9bc3d714b8"
      url "https://github.com/tesh254/raph/releases/download/v#{version}/raph_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c24cf0e5311a49bc1f41e190841123890cedc047c274fcc440100e9d96e22cfd"
      url "https://github.com/tesh254/raph/releases/download/v#{version}/raph_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "33a9a97459a992a2dc6c394077bd3e24d5726b6a662e434c67d5699207075c5d"
      url "https://github.com/tesh254/raph/releases/download/v#{version}/raph_linux_arm64.tar.gz"
    end
  end

  name "raph"
  desc "Local-first graph-vector brain for coding agents"
  homepage "https://tesh254.github.io/raph/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "raph"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/raph"]
    end
  end

  # No zap stanza required

end
